# Generated by Django 3.0.1 on 2020-01-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='name',
        ),
        migrations.AddField(
            model_name='list',
            name='ft_follow',
            field=models.CharField(default='NULL', max_length=120),
        ),
        migrations.AddField(
            model_name='list',
            name='ft_like',
            field=models.CharField(default='NULL', max_length=120),
        ),
        migrations.AddField(
            model_name='list',
            name='ft_view',
            field=models.CharField(default='NULL', max_length=120),
        ),
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
