# Generated by Django 3.0.1 on 2020-01-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20200109_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='follow',
            field=models.CharField(default='NULL', max_length=120),
        ),
        migrations.AddField(
            model_name='list',
            name='like',
            field=models.CharField(default='NULL', max_length=120),
        ),
        migrations.AddField(
            model_name='list',
            name='view',
            field=models.CharField(default='NULL', max_length=120),
        ),
    ]
