# Generated by Django 3.0.1 on 2020-01-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20200109_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bottype', models.IntegerField(default='NULL', max_length=120)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FreeTrialFollow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='NULL', max_length=120)),
                ('time', models.CharField(default='NULL', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='FreeTrialView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='NULL', max_length=120)),
                ('time', models.CharField(default='NULL', max_length=120)),
            ],
        ),
    ]
