# Generated by Django 3.0.1 on 2020-01-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_bots_freetrialfollow_freetrialview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='bottype',
            field=models.IntegerField(default=0),
        ),
    ]
