# Generated by Django 3.0.1 on 2020-01-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_auto_20200115_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NULL', max_length=120, unique=True)),
                ('time', models.CharField(default='NULL', max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='FreeTrialFollow',
        ),
        migrations.DeleteModel(
            name='FreeTrialView',
        ),
        migrations.RemoveField(
            model_name='bots',
            name='active',
        ),
        migrations.RemoveField(
            model_name='bots',
            name='bottype',
        ),
        migrations.AddField(
            model_name='bots',
            name='time',
            field=models.CharField(default='NULL', max_length=120),
        ),
        migrations.AddField(
            model_name='bots',
            name='username',
            field=models.CharField(default='NULL', max_length=120),
        ),
    ]
