# Generated by Django 3.0.1 on 2020-01-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_auto_20200116_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='bots',
            name='kind',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queue',
            name='kind',
            field=models.IntegerField(default=0),
        ),
    ]
