# Generated by Django 3.0.1 on 2020-01-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_auto_20200116_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='bots',
            name='name',
            field=models.CharField(default='NULL', max_length=120),
        ),
    ]
